[mcp_servers.UnityMCP]
command = 'C:\Users\ADMIN\.local\bin\uvx.exe'
args = [
    "--no-cache",
    "--refresh",
    "--from",
    "mcpforunityserver==9.7.3",
    "mcp-for-unity",
    "--default-instance",
    "6401",
]
